---Generates a table of Highlight groups and their respective definitions
---from a palette of colors and a highlighting function.
---@private
---@param colors Colors # palette of colors
---@param highlight fun(group: string, style: table<string, any>): nil # highlighting function
return function(colors, highlight)
	local C             = colors
	local default       = { fg = C.fg1, bg = C.bg1 }
	local muted         = { fg = C.fg2 }
	local selection     = { bg = C.selection_bg }
	local current_line  = { fg = C.fg1, bg = C.selection_bg }
	local search        = { fg = C.bg3, bg = C.yellow2, bold = true }
	local ui_title      = { fg = C.fg2, bold = true }
	local ui_select     = { bg = C.bg1, fg = C.fg1 }
	local ui_thumb      = { bg = C.bg3, fg = C.bg1 }
	local text_selected = { bg = C.fg4 }

	highlight('Normal', default)
	highlight('Visual', selection)
	highlight('Pmenu', { bg = C.bg3 })
	highlight('NormalFloat', { link = 'Pmenu' })
	highlight('WildMenu', { link = 'Pmenu' })
	highlight('NonText', { fg = C.fg4 })
	highlight('FloatBorder', { fg = "#576C85" })
	highlight('PmenuSel', ui_select)
	highlight('PmenuSbar', ui_thumb)
	highlight('PmenuThumb', text_selected)
	highlight('Whitespace', { link = 'NonText' })
	highlight('Conceal', { link = 'NonText' })
	highlight('WinSeparator', { link = 'NonText' })
	highlight('VertSplit', { link = 'NonText' })
	highlight('CursorLineNr', current_line)
	highlight('CursorLine', selection)
	highlight('CursorColumn', selection)
	highlight('CursorColumn', selection)
	highlight('ColorColumn', selection)
	highlight('SignColumn', default)
	highlight('CursorLineFold', default)
	highlight('LineNr', current_line)
	highlight('LineNrAbove', muted)
	highlight('LineNrBelow', muted)
	highlight('DiffAdd', { fg = 'NONE', bg = C.diff_add })
	highlight('DiffDelete', { fg = 'NONE', bg = C.diff_remove })
	highlight('DiffText', { fg = 'NONE', bg = C.diff_text })
	highlight('Directory', { fg = C.cyan1 })
	highlight('EndOfBuffer', { link = 'NonText' })
	highlight('Error', { fg = C.orange })
	highlight('ErrorMsg', { fg = C.red2 })
	highlight('Folded', muted)
	highlight('FoldColumn', muted)
	highlight('ModeMsg', { fg = C.fg2 })
	highlight('MoreMsg', { fg = C.fg1 })
	highlight('Question', { fg = C.magenta })
	highlight('Search', search)
	highlight('IncSearch', search)
	highlight('Substitute', search)
	highlight('SpellBad', { sp = C.red2, undercurl = true })
	highlight('SpellCap', { sp = C.yellow2, undercurl = true })
	highlight('SpellLocal', { sp = C.cyan2, undercurl = true })
	highlight('SpellRare', { sp = C.magenta, undercurl = true })
	highlight('StatusLine', { fg = C.fg2, bg = C.bg1 })
	highlight('StatusLineNC', { fg = C.fg2, bg = C.bg3 })
	highlight("WinBar", { link = "StatusLine" })
	highlight("WinBarNC", { link = "StatusLine" })
	highlight("StatusBlack", { fg = C.fg3, bg = C.bg1 })
	highlight("StatusRed", { fg = C.red2, bg = C.bg1 })
	highlight("StatusGreen", { fg = C.green, bg = C.bg1 })
	highlight("StatusYellow", { fg = C.yellow2, bg = C.bg1 })
	highlight("StatusBlue", { fg = C.blue2, bg = C.bg1 })
	highlight("StatusMagenta", { fg = C.magenta, bg = C.bg1 })
	highlight("StatusCyan", { fg = C.cyan2, bg = C.bg1 })
	highlight("StatusWhite", { fg = 'fg', bg = C.bg1 })
	highlight("StatusOrange", { fg = C.orange, bg = C.bg1 })
	highlight('TabLine', { fg = C.fg2, bg = C.bg1 })
	highlight('TabLineFill', { fg = C.fg3, bg = C.bg1 })
	highlight('TabLineSel', default)
	highlight('WarningMsg', { fg = C.yellow3, bg = C.bg3 })
	highlight('MatchParen', { bold = true })
	highlight('DiagnosticError', { fg = C.red1, bg = 'NONE' })
	highlight('DiagnosticSignError', { fg = C.red1, bold = true, bg = 'NONE' })
	highlight('DiagnosticUnderlineError', { undercurl = true })
	highlight('DiagnosticVirtualTextError', { fg = C.red1, bg = 'NONE' })
	highlight('DiagnosticHint', { fg = C.cyan1, bg = 'NONE' })
	highlight('DiagnosticSignHint', { fg = C.cyan1, bold = true, bg = 'NONE' })
	highlight('DiagnosticUnderlineHint', {})
	highlight('DiagnosticVirtualTextHint', { fg = C.cyan1, bg = 'NONE' })
	highlight('DiagnosticInfo', { fg = C.green, bg = 'NONE' })
	highlight('DiagnosticSignInfo', { fg = C.green, bold = true, bg = 'NONE' })
	highlight('DiagnosticUnderlineInfo', {})
	highlight('DiagnosticVirtualTextInfo', { fg = C.green, bg = 'NONE' })
	highlight('DiagnosticWarn', { fg = C.yellow1, bg = 'NONE' })
	highlight('DiagnosticSignWarn', { fg = C.yellow1, bold = true, bg = 'NONE' })
	highlight('DiagnosticUnderlineWarn', {})
	highlight('DiagnosticVirtualTextWarn', { fg = C.yellow1, bg = 'NONE' })
	highlight('LspReferenceText', { underline = true, sp = C.fg3, bg = 'NONE', fg = 'NONE' })
	highlight('LspReferenceRead', { underline = true, sp = C.fg3, bg = 'NONE', fg = 'NONE' })
	highlight('LspReferenceWrite', { underline = true, sp = C.fg3, bg = 'NONE', fg = 'NONE' })
	highlight('TelescopeBorder', { link = 'NonText' })
	highlight('TelescopeTitle', ui_title)
	highlight('TelescopePromptCounter', { fg = C.fg2 })
	highlight('TelescopeMatching', { bg = C.bg2 })
	highlight('TelescopeSelectionCaret', { fg = C.fg2 })
	highlight('TelescopeSelection', text_selected)
	highlight('FloatTitle', ui_title)
	highlight('FocusedSymbol', text_selected)
	highlight('TroubleIndent', { bg = C.bg2 })

	highlight('NeogitSectionHeader', { fg = C.red1 })
	highlight('NeogitPopupActionKey', { fg = C.red1 })
	highlight('NeogitChangeModified', { fg = C.cyan1, italic = true })
	highlight('NeogitBranchHead', { fg = C.cyan1 })
	highlight('NeogitBranch', { fg = C.cyan1 })


	highlight("Statement", { fg = C.fg1 })
	highlight("String", { fg = C.green })
	highlight("Comment", { fg = C.fg2 })
	--highlight("PreProc", { fg = C.red1 })
	highlight("PreProc", { fg = C.fg1 })
	highlight("Operator", { fg = C.fg3 })
	highlight("StorageClass", { fg = C.fg1 })
	highlight("Function", { fg = C.blue1 })
	highlight("Identifier", { fg = C.fg1 })
	highlight("Type", { fg = C.yellow1 })
	highlight("Number", { fg = C.fg1 })
	highlight("Special", { fg = C.cyan1 })

	highlight("@lsp.type.builtin", { fg = C.blue1, italic = true })
	highlight("@lsp.type.number", { fg = C.fg1 })
	highlight("@lsp.type.function.declaration", { fg = C.cyan1 })
	highlight("@lsp.type.function.definition", { fg = C.cyan1 })

	-- C specific
	highlight("cInclude", { fg = C.red1 })
	highlight("cDefine", { fg = C.cyan1 })
	highlight("cLabel", { fg = C.fg1 })
	highlight("cStructure", { fg = C.yellow2 })
	highlight("cStorageClass", { fg = C.yellow2 })
	highlight("@lsp.mod.defaultLibrary.c", { italic = true })
	--highlight("@lsp.mod.declaration.c", { fg = C.cyan1 })
	--highlight("@lsp.mod.definition.c", { fg = C.cyan1 })
	highlight("@lsp.type.macro.c", { fg = C.magenta1 })
	highlight("@lsp.type.enumMember.c", { fg = C.blue1 })
	highlight("@lsp.typemod.function.declaration.c", { fg = C.cyan1 })
	highlight("@lsp.typemod.parameter.definition.c", { fg = C.fg1 })
	highlight("@lsp.typemod.parameter.declaration.c", { fg = C.fg1 })
	highlight("@lsp.typemod.variable.definition.c", { fg = C.fg1 })
	highlight("@lsp.typemod.variable.declaration.c", { fg = C.fg1 })
	highlight("@lsp.typemod.property.declaration.c", { fg = C.fg1 })
	highlight("@lsp.typemod.macro.declaration.c", { fg = C.fg1 })
	highlight("@lsp.typemod.enum.declaration.c", { fg = C.yellow1 })
	highlight("@lsp.typemod.enumMember.declaration.c", { fg = C.fg1 })

	-- Zig specific
	highlight("zigConditional", { fg = C.fg1 })
	highlight("@lsp.type.keyword.zig", { fg = C.red1 })
	highlight("@lsp.mod.declaration.zig", { fg = C.cyan1 })
	highlight("@lsp.type.property.zig", { fg = C.fg1 })
	highlight("@lsp.type.enumMember.zig", { fg = C.blue1 })
	highlight("@lsp.type.method.zig", { fg = C.cyan1 })
	highlight("@lsp.typemod.property.declaration.zig", { fg = C.fg1 })
	highlight("@lsp.typemod.struct.declaration.zig", { fg = C.fg1 })
	highlight("@lsp.typemod.parameter.declaration.zig", { fg = C.fg1 })
	highlight("@lsp.typemod.namespace.declaration.zig", { fg = C.fg1 })
	highlight("@lsp.typemod.variable.declaration.zig", { fg = C.fg1 })
	highlight("@lsp.typemod.enum.declaration.zig", { fg = C.fg1 })
	highlight("@lsp.typemod.enumMember.declaration.zig", { fg = C.fg1 })

	-- Go specific
	highlight("goVarDefs", { fg = C.fg1 })
	highlight("goVarAssign", { fg = C.fg1 })
	highlight("goFunction", { fg = C.cyan1 })

	--
	highlight("yamlBool", { fg = C.red1 })
	highlight("yamlInteger", { fg = C.yellow2 })


	--highlight("@lsp.type.keyword", { fg = C.red1 })
	--highlight("@lsp.type.operator", { fg = C.red1 })
	--highlight("@lsp.type.method", { fg = C.cyan1 })
	--highlight("@lsp.type.function", { fg = C.cyan1 })
	--highlight("@lsp.type.property", { fg = C.fg1 })
	--highlight("@lsp.type.struct", { fg = C.yellow2 })
	--highlight("@lsp.type.namespace", { fg = C.yellow2 })
	--highlight("@lsp.type.type", { fg = C.yellow2 })
	--highlight("@lsp.type.enum", { fg = C.yellow2 })
	--highlight("@lsp.type.enumMember", { fg = C.blue1 })
	--highlight("@lsp.type.string", { fg = C.green })
end
